//
//  Services/CodeGeneratorService.swift
//  TheWorkshop-iOS
//  Generates Logos / Theos / Jailed / SwiftUI Code
//

import Foundation

public class CodeGeneratorService {
    public static let shared = CodeGeneratorService()

    public func generateLogosCode(for project: Project) -> String {
        var code = ""
        code += "//\n"
        code += "//  Tweak.x\n"
        code += "//  Project: \(project.name) (\(project.version))\n"
        code += "//  Target: \(project.targetProcess) (\(project.bundleId))\n"
        code += "//  Generated by The Workshop Native iOS Application\n"
        code += "//\n\n"
        code += "#import <Foundation/Foundation.h>\n"
        code += "#import <UIKit/UIKit.h>\n"
        code += "#import <os/log.h>\n\n"

        // Group hooks by class or group
        let hookBlocks = project.blocks.filter { $0.type == .hook }
        
        if hookBlocks.isEmpty {
            code += "// No %hook blocks currently configured on canvas.\n\n"
        }

        for hook in hookBlocks {
            let className = hook.targetClass ?? "UIViewController"
            let methodName = hook.targetMethod ?? "viewDidAppear:"
            let isClass = hook.isClassMethod ?? false
            let methodPrefix = isClass ? "+" : "-"
            let retType = hook.returnType ?? "void"

            code += "%hook \(className)\n\n"
            code += "\(methodPrefix) (\(retType))\(methodName) {\n"

            // Look for attached child blocks or subsequent blocks
            let childIds = hook.childrenBlockIds ?? []
            let childBlocks = project.blocks.filter { childIds.contains($0.id) }

            if childBlocks.isEmpty {
                code += "    %orig;\n"
                code += "    NSLog(@\"[TheWorkshop] \(className) \(methodName) executed\");\n"
            } else {
                for child in childBlocks {
                    code += generateBlockSnippet(child, indent: "    ")
                }
            }

            code += "}\n\n"
            code += "%end // \(className)\n\n"
        }

        // Check for constructors (%ctor)
        let ctors = project.blocks.filter { $0.type == .constructor }
        if !ctors.isEmpty {
            for ctor in ctors {
                code += "%ctor {\n"
                code += "    NSLog(@\"[TheWorkshop] Dynamic library loaded for process \(project.targetProcess)\");\n"
                if let custom = ctor.customCode {
                    code += "    \(custom)\n"
                }
                code += "}\n\n"
            }
        }

        return code
    }

    private func generateBlockSnippet(_ block: Block, indent: String) -> String {
        var snippet = ""
        switch block.type {
        case .orig:
            if let assign = block.assignToVar, !assign.isEmpty {
                snippet += "\(indent)id \(assign) = %orig;\n"
            } else {
                snippet += "\(indent)%orig;\n"
            }
        case .log:
            let msg = block.message ?? "Hook trigger"
            let level = block.logLevel ?? "NSLog"
            if level == "os_log" {
                snippet += "\(indent)os_log(OS_LOG_DEFAULT, \"[TheWorkshop] \(msg)\");\n"
            } else {
                snippet += "\(indent)NSLog(@\"[TheWorkshop] \(msg)\");\n"
            }
        case .modifyProperty:
            let obj = block.targetObject ?? "self"
            let prop = block.propertyName ?? "backgroundColor"
            let val = block.value ?? "[UIColor systemPinkColor]"
            snippet += "\(indent)\(obj).\(prop) = \(val);\n"
        case .conditional:
            let cond = block.condition ?? "YES"
            snippet += "\(indent)if (\(cond)) {\n"
            snippet += "\(indent)    NSLog(@\"[TheWorkshop] Condition (\(cond)) passed\");\n"
            snippet += "\(indent)}\n"
        case .delay:
            let duration = block.durationSeconds ?? 1.0
            snippet += "\(indent)dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(\(duration) * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{\n"
            snippet += "\(indent)    NSLog(@\"[TheWorkshop] Delayed execution completed\");\n"
            snippet += "\(indent)});\n"
        case .notification:
            let title = block.titleText ?? "Tweak Alert"
            let body = block.bodyText ?? "Executed"
            snippet += "\(indent)UIAlertController *alert = [UIAlertController alertControllerWithTitle:@\"\(title)\" message:@\"\(body)\" preferredStyle:UIAlertControllerStyleAlert];\n"
            snippet += "\(indent)[alert addAction:[UIAlertAction actionWithTitle:@\"OK\" style:UIAlertActionStyleDefault handler:nil]];\n"
            snippet += "\(indent)[(UIViewController *)self presentViewController:alert animated:YES completion:nil];\n"
        case .returnValue:
            let val = block.returnValue ?? "YES"
            snippet += "\(indent)return \(val);\n"
        case .customLogos:
            if let custom = block.customCode {
                snippet += "\(indent)\(custom)\n"
            }
        default:
            break
        }
        return snippet
    }

    public func generateMakefile(for project: Project) -> String {
        let cleanName = project.name.replacingOccurrences(of: " ", with: "")
        return """
        TARGET := iphone:clang:latest:15.0
        INSTALL_TARGET_PROCESSES = \(project.targetProcess)

        include $(THEOS)/makefiles/common.mk

        TWEAK_NAME = \(cleanName)

        \(cleanName)_FILES = Tweak.x
        \(cleanName)_CFLAGS = -fobjc-arc

        include $(THEOS_MAKEFILE_PATH)/tweak.mk
        """
    }

    public func generateControlFile(for project: Project) -> String {
        let cleanName = project.name.replacingOccurrences(of: " ", with: "").lowercased()
        return """
        Package: \(project.bundleId)
        Name: \(project.name)
        Depends: mobilesubstrate (>= 0.9.5000), firmware (>= 15.0)
        Version: \(project.version)
        Architecture: iphoneos-arm
        Description: \(project.description)
        Maintainer: \(project.author)
        Author: \(project.author)
        Section: Tweaks
        """
    }

    public func generatePlistFilter(for project: Project) -> String {
        return """
        { Filter = { Bundles = ( "\(project.tweakFilter)" ); }; }
        """
    }

    public func generateJailedPatchScript(for project: Project) -> String {
        let cleanName = project.name.replacingOccurrences(of: " ", with: "")
        let assetBlocks = project.blocks.filter { $0.type == .replaceAsset }
        let plistBlocks = project.blocks.filter { $0.type == .editPlist }

        var script = """
        #!/usr/bin/env bash
        # ==============================================================================
        # \(project.name) - Jailed IPA Patching Script
        # Target: \(project.targetProcess) (\(project.bundleId))
        # Generated by The Workshop Native iOS Application
        # ==============================================================================

        set -e

        IPA_INPUT="TargetApp.ipa"
        IPA_OUTPUT="\(cleanName)_Modified.ipa"
        DYLIB_NAME="\(cleanName).dylib"

        echo "[1/4] Unpacking target IPA bundle..."
        rm -rf extracted
        unzip -q "$IPA_INPUT" -d extracted

        echo "[2/4] Applying asset replacements..."
        """

        for asset in assetBlocks {
            let path = asset.assetPath ?? "Assets.car"
            let replace = asset.replacementUrl ?? "new_icon.png"
            script += "\ncp -f \"assets/\(replace)\" \"extracted/Payload/\(project.targetProcess).app/\(path)\""
        }

        script += "\n\necho \"[3/4] Modifying Info.plist metadata...\""

        for plist in plistBlocks {
            let key = plist.plistKey ?? "CFBundleDisplayName"
            let val = plist.plistValue ?? "Modded App"
            script += "\n/usr/libexec/PlistBuddy -c \"Set :\(key) '\(val)'\" \"extracted/Payload/\(project.targetProcess).app/Info.plist\" || /usr/libexec/PlistBuddy -c \"Add :\(key) string '\(val)'\" \"extracted/Payload/\(project.targetProcess).app/Info.plist\""
        }

        script += """


        echo "[4/4] Injecting dynamic library and repacking..."
        if [ -f "$DYLIB_NAME" ]; then
            optool inject -s -t "extracted/Payload/\(project.targetProcess).app/\(project.targetProcess)" -p "@executable_path/$DYLIB_NAME"
        fi

        cd extracted
        zip -qr "../$IPA_OUTPUT" Payload
        cd ..

        echo "SUCCESS! Modified IPA created: $IPA_OUTPUT"
        """

        return script
    }

    public func generateSwiftUIExtensionCode(for project: Project) -> String {
        let cleanName = project.name.replacingOccurrences(of: " ", with: "")
        let swiftuiBlocks = project.blocks.filter { $0.type == .swiftuiView }

        var code = """
        //
        //  \(cleanName)Extension.swift
        //  Native iOS SwiftUI Extension Target
        //  Generated by The Workshop Native iOS Application
        //

        import WidgetKit
        import SwiftUI

        @main
        struct \(cleanName)Extension: Widget {
            let kind: String = "com.apple.widgetkit-extension"

            var body: some WidgetConfiguration {
                StaticConfiguration(kind: kind, provider: WorkshopProvider()) { entry in
                    \(swiftuiBlocks.first?.viewTitle ?? "\(cleanName)WidgetView")()
                }
                .configurationDisplayName("\(project.name)")
                .description("\(project.description)")
                .supportedFamilies([.systemSmall, .systemMedium, .accessoryCircular])
            }
        }

        struct WorkshopProvider: TimelineProvider {
            func placeholder(in context: Context) -> WorkshopEntry {
                WorkshopEntry(date: Date())
            }

            func getSnapshot(in context: Context, completion: @escaping (WorkshopEntry) -> Void) {
                completion(WorkshopEntry(date: Date()))
            }

            func getTimeline(in context: Context, completion: @escaping (Timeline<WorkshopEntry>) -> Void) {
                completion(Timeline(entries: [WorkshopEntry(date: Date())], policy: .atEnd))
            }
        }

        struct WorkshopEntry: TimelineEntry {
            let date: Date
        }

        """

        if swiftuiBlocks.isEmpty {
            code += """
            struct \(cleanName)WidgetView: View {
                var body: some View {
                    VStack {
                        Text("\(project.name)")
                            .font(.headline)
                            .foregroundStyle(.pink)
                        Text("Native Extension Target")
                            .font(.caption)
                            .foregroundStyle(.green)
                    }
                    .containerBackground(.black, for: .widget)
                }
            }
            """
        } else {
            for block in swiftuiBlocks {
                let title = block.viewTitle ?? "WorkshopView"
                let body = block.swiftuiCode ?? "Text(\"Hello Native Extension\")"
                code += """

                struct \(title): View {
                    var body: some View {
                        VStack(alignment: .leading, spacing: 6) {
                            \(body)
                        }
                        .padding()
                        .background(Color.black)
                    }
                }
                """
            }
        }

        return code
    }
}
