import React, { useState } from "react";
import { Project, BlockData } from "../types";
import { generateLogosCode } from "../utils/codeGenerator";
import {
  Smartphone,
  Code2,
  Play,
  Plus,
  Terminal,
  Cpu,
  Layers,
  Sliders,
  Copy,
  Check,
  Zap,
  RotateCcw
} from "lucide-react";

interface SwiftUICompanionProps {
  project: Project;
  onUpdateBlock: (updated: BlockData) => void;
  onRunSimulation: () => void;
}

export const SwiftUICompanion: React.FC<SwiftUICompanionProps> = ({
  project,
  onUpdateBlock,
  onRunSimulation,
}) => {
  const [companionTab, setCompanionTab] = useState<"simulator" | "swift_code">("simulator");
  const [selectedSimBlockId, setSelectedSimBlockId] = useState<string | null>(project.blocks[0]?.id || null);
  const [simLogOutput, setSimLogOutput] = useState<string[]>([]);
  const [copiedCode, setCopiedCode] = useState(false);

  const selectedSimBlock = project.blocks.find((b) => b.id === selectedSimBlockId);

  const swiftSourceCode = `//
// TheWorkshopApp.swift
// The Workshop iOS Companion (Native SwiftUI Edition)
// Architecture: MVVM + Shared JSON Schema
//

import SwiftUI
import Combine

// MARK: - Models
struct TweakProject: Codable, Identifiable {
    let id: String
    var name: String
    var bundleId: String
    var targetProcess: String
    var blocks: [TweakBlock]
}

struct TweakBlock: Codable, Identifiable {
    let id: String
    var type: String
    var title: String
    var targetClass: String?
    var targetMethod: String?
    var message: String?
    var durationSeconds: Double?
}

// MARK: - ViewModel
class ProjectViewModel: ObservableObject {
    @Published var project: TweakProject
    @Published var generatedLogosCode: String = ""
    
    init(project: TweakProject) {
        self.project = project
        self.generateLogos()
    }
    
    func generateLogos() {
        var code = "// Generated by The Workshop iOS SwiftUI\\n"
        for block in project.blocks {
            if block.type == "hook" {
                code += "%hook \\(block.targetClass ?? "UIViewController")\\n"
                code += "- (void)\\(block.targetMethod ?? "viewDidAppear:") {\\n"
                code += "    %orig;\\n"
                code += "    NSLog(@\\"[TheWorkshop iOS] Executed!\\");\\n"
                code += "}\\n%end\\n"
            }
        }
        self.generatedLogosCode = code
    }
}

// MARK: - SwiftUI Root View
struct ContentView: View {
    @StateObject var viewModel: ProjectViewModel
    
    var body: some View {
        NavigationStack {
            ZStack {
                Color.black.ignoresSafeArea()
                
                VStack(spacing: 16) {
                    // Header
                    HStack {
                        Image(systemName: "cpu.fill")
                            .foregroundColor(.green)
                        Text(viewModel.project.name)
                            .font(.headline)
                            .foregroundColor(.white)
                        Spacer()
                    }
                    .padding()
                    .background(Color.zinc900)
                    .cornerRadius(12)
                    
                    // Blocks List
                    ScrollView {
                        VStack(spacing: 12) {
                            ForEach(viewModel.project.blocks) { block in
                                BlockRowView(block: block)
                            }
                        }
                    }
                }
                .padding()
            }
            .navigationTitle("The Workshop")
        }
    }
}

struct BlockRowView: View {
    let block: TweakBlock
    
    var body: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                Text(block.title)
                    .font(.caption)
                    .bold()
                    .foregroundColor(.green)
                if let cls = block.targetClass {
                    Text(cls).font(.caption2).foregroundColor(.gray)
                }
            }
            Spacer()
        }
        .padding()
        .background(Color.zinc950)
        .overlay(RoundedRectangle(cornerRadius: 10).stroke(Color.green.opacity(0.3)))
    }
}
`;

  const runSim = () => {
    const logs = [
      `[SIMULATOR] Booting iOS 18.0 SpringBoard runtime...`,
      `[SIMULATOR] Injecting ${project.name} (${project.bundleId})...`,
      `[LOGOS] Hooking class: ${project.blocks[0]?.targetClass || "UIViewController"}`,
      `[LOGOS] Method swizzling: ${project.blocks[0]?.targetMethod || "viewDidAppear:"}`,
      `[SYSTEM] %orig executed successfully.`,
      `[NSLog] ${project.blocks.find((b) => b.type === "log")?.message || "Tweak execution complete."}`,
      `[SUCCESS] Tweak simulation active!`
    ];
    setSimLogOutput(logs);
  };

  return (
    <div className="w-full h-[calc(100vh-3rem)] bg-[#050505] text-gray-200 font-mono flex flex-col">
      {/* Header Bar */}
      <div className="min-h-10 h-auto py-1.5 px-3 sm:px-6 bg-[#0a0a0a] border-b border-[#222] flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
        <div className="flex items-center space-x-2">
          <Smartphone className="w-3.5 h-3.5 text-[#FF69B4]" />
          <span className="font-bold text-[11px] sm:text-xs text-[#FF69B4] uppercase tracking-wider">
            WORKSHOP iOS APP (SWIFTUI)
          </span>
        </div>

        <div className="flex items-center space-x-1 bg-[#111] border border-[#222] p-0.5 rounded">
          <button
            onClick={() => setCompanionTab("simulator")}
            className={`px-2.5 sm:px-3 py-1 text-[9px] sm:text-[10px] rounded font-bold transition-all ${
              companionTab === "simulator"
                ? "bg-[#222] text-[#FF69B4] border border-[#FF69B4]"
                : "text-gray-500 hover:text-gray-300"
            }`}
          >
            Live Simulator
          </button>
          <button
            onClick={() => setCompanionTab("swift_code")}
            className={`px-2.5 sm:px-3 py-1 text-[9px] sm:text-[10px] rounded font-bold transition-all ${
              companionTab === "swift_code"
                ? "bg-[#222] text-[#39FF14] border border-[#39FF14]"
                : "text-gray-500 hover:text-gray-300"
            }`}
          >
            Swift / SwiftUI Source
          </button>
        </div>
      </div>

      {companionTab === "simulator" ? (
        <div className="flex-1 p-3 sm:p-6 flex flex-col md:flex-row items-center justify-center gap-6 md:gap-8 overflow-y-auto">
          {/* iPhone Mockup Frame */}
          <div className="w-[280px] sm:w-[320px] h-[520px] sm:h-[640px] bg-black border-[4px] border-[#222] rounded-[36px] sm:rounded-[40px] shadow-[0_0_40px_rgba(255,105,180,0.15)] flex flex-col overflow-hidden relative shrink-0">
            {/* Dynamic Island */}
            <div className="w-24 h-5 bg-black rounded-full mx-auto my-2 border border-[#222] z-30 flex items-center justify-center">
              <div className="w-2 h-2 bg-[#222] rounded-full" />
            </div>

            {/* iOS App Viewport */}
            <div className="flex-1 bg-black p-4 flex flex-col justify-between overflow-y-auto font-sans">
              <div className="space-y-3">
                {/* App Navigation Bar */}
                <div className="flex items-center justify-between pb-2 border-b border-[#222]">
                  <div className="flex items-center space-x-2">
                    <Cpu className="w-4 h-4 text-[#39FF14]" />
                    <span className="font-bold text-xs text-white uppercase">{project.name}</span>
                  </div>
                  <span className="px-2 py-0.5 text-[9px] bg-[#111] text-[#39FF14] border border-[#222] rounded font-mono">
                    iOS 18.0
                  </span>
                </div>

                {/* Blocks Stack inside iPhone app */}
                <div className="space-y-2">
                  <div className="text-[9px] text-gray-500 font-mono uppercase tracking-widest font-bold">
                    Visual Blocks Tree ({project.blocks.length})
                  </div>

                  {project.blocks.map((block) => (
                    <div
                      key={block.id}
                      onClick={() => setSelectedSimBlockId(block.id)}
                      className={`p-2.5 rounded border text-xs cursor-pointer transition-all ${
                        selectedSimBlockId === block.id
                          ? "bg-[#111] border-[#FF69B4] text-[#FF69B4] shadow-[0_0_10px_rgba(255,105,180,0.2)]"
                          : "bg-black border-[#222] text-gray-300 hover:border-[#333]"
                      }`}
                    >
                      <div className="font-bold font-mono text-[11px] flex items-center justify-between">
                        <span>{block.title || block.type}</span>
                        <span className="text-[9px] text-gray-500 uppercase">{block.type}</span>
                      </div>
                      {block.targetClass && (
                        <div className="text-[9px] text-gray-500 font-mono mt-0.5 truncate">
                          {block.targetClass} → {block.targetMethod}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Mobile Simulation Control */}
              <div className="pt-3 border-t border-[#222]">
                <button
                  onClick={runSim}
                  className="w-full py-2 bg-[#39FF14] text-black font-bold text-xs rounded hover:bg-green-400 flex items-center justify-center space-x-2 transition-all uppercase tracking-wider"
                >
                  <Play className="w-3.5 h-3.5 fill-current" />
                  <span>Execute Mobile Tweak Test</span>
                </button>
              </div>
            </div>

            {/* Bottom Home Indicator */}
            <div className="w-28 h-1 bg-[#333] rounded-full mx-auto my-2" />
          </div>

          {/* Simulator Console Output */}
          <div className="w-full max-w-md h-[480px] bg-black border border-[#222] rounded p-4 flex flex-col font-mono text-xs">
            <div className="flex items-center justify-between pb-3 border-b border-[#222] text-gray-400">
              <span className="flex items-center space-x-2 text-[#39FF14] font-bold text-xs uppercase tracking-wider">
                <Terminal className="w-4 h-4 text-[#39FF14]" />
                <span>iOS Runtime Console Log</span>
              </span>
              <button
                onClick={runSim}
                className="px-2 py-1 bg-[#111] hover:bg-[#222] rounded text-[10px] text-gray-300 border border-[#222]"
              >
                Clear / Run
              </button>
            </div>

            <div className="flex-1 py-3 space-y-1.5 overflow-y-auto">
              {simLogOutput.length === 0 ? (
                <div className="text-gray-600 text-center pt-20 text-[11px]">
                  Click "Execute Mobile Tweak Test" on the iPhone simulator to run hook logic.
                </div>
              ) : (
                simLogOutput.map((log, idx) => (
                  <div
                    key={idx}
                    className={`text-[10px] ${
                      log.includes("LOGOS")
                        ? "text-[#39FF14] font-bold"
                        : log.includes("SUCCESS")
                        ? "text-[#FF69B4] font-bold"
                        : "text-gray-400"
                    }`}
                  >
                    {log}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      ) : (
        /* Swift Source Code View */
        <div className="flex-1 p-6 overflow-auto bg-black font-mono text-xs leading-relaxed">
          <div className="flex items-center justify-between mb-4 pb-2 border-b border-[#222]">
            <span className="text-[#39FF14] font-bold">TheWorkshopApp.swift (SwiftUI Native Code)</span>
            <button
              onClick={() => {
                navigator.clipboard.writeText(swiftSourceCode);
                setCopiedCode(true);
                setTimeout(() => setCopiedCode(false), 2000);
              }}
              className="px-3 py-1 bg-[#111] hover:bg-[#222] border border-[#222] rounded text-[10px] text-gray-300 font-bold"
            >
              {copiedCode ? "Copied!" : "Copy Swift Source"}
            </button>
          </div>
          <pre className="text-[#39FF14] whitespace-pre">
            <code>{swiftSourceCode}</code>
          </pre>
        </div>
      )}
    </div>
  );
};
