import { BlockData, Project } from "../types";

/**
 * Converts a The Workshop block graph into clean, idiomatic Logos / Theos syntax (%hook, %orig, NSLog, etc.)
 */
export function generateLogosCode(project: Project): string {
  const header = `//
// ${project.name}.x
// Generated by The Workshop (iOS Jailbreak Tweak Studio)
// Target Process: ${project.targetProcess}
// Bundle ID: ${project.bundleId}
// Author: ${project.author || "Jailbreak Developer"}
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <os/log.h>

// Filter Control: ${project.tweakFilter}

`;

  const rootHooks = project.blocks.filter((b) => b.type === "hook");
  const groups = project.blocks.filter((b) => b.type === "group");
  const constructors = project.blocks.filter((b) => b.type === "constructor");
  const annotations = project.blocks.filter((b) => b.type === "annotation");

  if (project.blocks.length === 0) {
    return header + `// No blocks defined yet.\n// Drag blocks onto the workspace to begin generating Logos code.\n`;
  }

  let bodyCode = "";

  // Render top-level canvas annotations as comments
  if (annotations.length > 0) {
    annotations.forEach((ann) => {
      bodyCode += `/*\n * ${ann.annotationText || "Canvas Note"}\n */\n\n`;
    });
  }

  // Render Groups if present
  groups.forEach((grp) => {
    bodyCode += `%group ${grp.groupName || "CustomGroup"}\n\n`;
  });

  // Render Root Hooks
  rootHooks.forEach((hookBlock) => {
    const cls = hookBlock.targetClass || "UIViewController";
    const method = hookBlock.targetMethod || "viewDidAppear:";
    const isClassMethod = hookBlock.isClassMethod ? "+" : "-";
    const returnType = hookBlock.returnType || "void";
    const params = hookBlock.methodParameters || "(BOOL)animated";

    bodyCode += `%hook ${cls}\n\n`;
    bodyCode += `${isClassMethod} (${returnType})${method}${params ? " " + params : ""} {\n`;

    // Generate code for children blocks connected to this hook
    const childrenCode = generateBlockSequenceCode(hookBlock.childrenBlockIds || [], project.blocks, 1);
    bodyCode += childrenCode;

    bodyCode += `}\n\n%end\n\n`;
  });

  if (groups.length > 0) {
    groups.forEach(() => {
      bodyCode += `%end // %group\n\n`;
    });
  }

  // Constructor / %ctor block
  if (constructors.length > 0) {
    constructors.forEach((ctor) => {
      bodyCode += `%ctor {\n    ${ctor.customCode || `NSLog(@"[The Workshop] Tweak loaded into target: ${project.targetProcess}");`}\n}\n`;
    });
  } else {
    bodyCode += `%ctor {\n    NSLog(@"[The Workshop] Tweak loaded into target: ${project.targetProcess}");\n}\n`;
  }

  return header + bodyCode;
}

function generateBlockSequenceCode(
  blockIds: string[],
  allBlocks: BlockData[],
  indentLevel: number
): string {
  let result = "";
  const indent = "    ".repeat(indentLevel);

  blockIds.forEach((id) => {
    const block = allBlocks.find((b) => b.id === id);
    if (!block) return;

    switch (block.type) {
      case "orig":
        if (block.assignToVar) {
          result += `${indent}id ${block.assignToVar} = %orig;\n`;
        } else {
          result += `${indent}%orig;\n`;
        }
        break;

      case "skip_orig":
        result += `${indent}// Skipped original method implementation (%orig ignored)\n`;
        break;

      case "log":
        const msg = block.message || "Method executed!";
        const level = block.logLevel || "NSLog";
        if (level === "NSLog") {
          result += `${indent}NSLog(@"[TheWorkshop] ${msg}");\n`;
        } else if (level === "os_log") {
          result += `${indent}os_log(OS_LOG_DEFAULT, "[TheWorkshop] ${msg}");\n`;
        } else {
          result += `${indent}HBLogDebug(@"[TheWorkshop] ${msg}");\n`;
        }
        break;

      case "modify_property":
        const targetObj = block.targetObject || "self";
        const prop = block.propertyName || "backgroundColor";
        const val = block.value || "[UIColor systemGreenColor]";
        result += `${indent}${targetObj}.${prop} = ${val};\n`;
        break;

      case "conditional":
        const cond = block.condition || "self.view != nil";
        result += `${indent}if (${cond}) {\n`;
        if (block.childrenBlockIds && block.childrenBlockIds.length > 0) {
          result += generateBlockSequenceCode(block.childrenBlockIds, allBlocks, indentLevel + 1);
        } else {
          result += `${indent}    NSLog(@"[TheWorkshop] Condition met: ${cond}");\n`;
        }
        result += `${indent}}\n`;
        break;

      case "delay":
        const sec = block.durationSeconds || 1.5;
        result += `${indent}dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(${sec} * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{\n`;
        if (block.childrenBlockIds && block.childrenBlockIds.length > 0) {
          result += generateBlockSequenceCode(block.childrenBlockIds, allBlocks, indentLevel + 1);
        } else {
          result += `${indent}    NSLog(@"[TheWorkshop] Executed after ${sec}s delay");\n`;
        }
        result += `${indent}});\n`;
        break;

      case "notification":
        const title = block.titleText || "Tweak Alert";
        const body = block.bodyText || "The Workshop tweak notification trigger";
        result += `${indent}dispatch_async(dispatch_get_main_queue(), ^{\n`;
        result += `${indent}    UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"${title}" message:@"${body}" preferredStyle:UIAlertControllerStyleAlert];\n`;
        result += `${indent}    [alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];\n`;
        result += `${indent}    [[[UIApplication sharedApplication] keyWindow].rootViewController presentViewController:alert animated:YES completion:nil];\n`;
        result += `${indent}});\n`;
        break;

      case "return_value":
        const retVal = block.returnValue || "YES";
        result += `${indent}return ${retVal};\n`;
        break;

      case "custom_logos":
        if (block.customCode) {
          const lines = block.customCode.split("\n");
          lines.forEach((line) => {
            result += `${indent}${line}\n`;
          });
        }
        break;

      case "replace_asset":
        result += `${indent}// Jailed Mod: Replace asset "${block.assetPath || "Assets.car"}" with "${block.replacementUrl || "custom_asset"}"\n`;
        result += `${indent}NSString *customPath = [[NSBundle mainBundle] pathForResource:@"${block.replacementUrl || "custom_asset"}" ofType:nil];\n`;
        result += `${indent}if (customPath) { NSLog(@"[TheWorkshop JailedMod] Overriding asset: ${block.assetPath || "asset"}"); }\n`;
        break;

      case "edit_plist":
        result += `${indent}// Jailed Mod Plist Override: ${block.plistKey || "Key"} = ${block.plistValue || "Value"}\n`;
        result += `${indent}[[[NSBundle mainBundle] infoDictionary] setValue:@"${block.plistValue || "true"}" forKey:@"${block.plistKey || "UIRequiresFullScreen"}"];\n`;
        break;

      case "swiftui_view":
        result += `${indent}// Native Extension SwiftUI View: ${block.viewTitle || "WorkshopWidgetView"}\n`;
        result += `${indent}// Declarative SwiftUI body: ${block.swiftuiCode || "Text(\"Widget\")"}\n`;
        break;

      case "extension_config":
        result += `${indent}// Extension Identifier: ${block.extensionKind || "com.apple.widgetkit-extension"}\n`;
        break;
    }

    // Follow nextBlockId chain if chained linearly
    if (block.nextBlockId) {
      result += generateBlockSequenceCode([block.nextBlockId], allBlocks, indentLevel);
    }
  });

  return result;
}

/**
 * Generates Makefile string for Theos builds
 */
export function generateTheosMakefile(project: Project): string {
  return `TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = ${project.targetProcess}

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ${project.name.replace(/\s+/g, "")}

${project.name.replace(/\s+/g, "")}_FILES = ${project.name.replace(/\s+/g, "")}.x
${project.name.replace(/\s+/g, "")}_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
${project.name.replace(/\s+/g, "")}_FRAMEWORKS = UIKit Foundation AudioToolbox

include $(THEOS_MAKE_PATH)/tweak.mk
`;
}

/**
 * Generates control file for Debian package (.deb) creation
 */
export function generateControlFile(project: Project): string {
  return `Package: ${project.bundleId}
Name: ${project.name}
Depends: mobilesubstrate (>= 0.9.5000), firmware (>= 14.0)
Version: ${project.version}
Architecture: iphoneos-arm64
Description: ${project.description || "Created with The Workshop visual tweak studio."}
Maintainer: ${project.author || "Jailbreak Developer"}
Author: ${project.author || "Jailbreak Developer"}
Section: Tweaks
`;
}

/**
 * Generates plist filter file
 */
export function generatePlistFilter(project: Project): string {
  return `{ Filter = { Bundles = ( "${project.tweakFilter}" ); }; }`;
}

/**
 * Generates native Swift Codable models for iOS
 */
export function generateSwiftModelsCode(project: Project): string {
  return `//
// TweakModels.swift
// ${project.name} iOS Native Codable Specifications
//

import Foundation

public struct TweakProject: Codable, Identifiable {
    public let id: String
    public var name: String
    public var bundleId: String
    public var version: String
    public var targetProcess: String
    public var tweakFilter: String
    public var blocks: [TweakBlock]

    public init(id: String = UUID().uuidString, name: String, bundleId: String, version: String, targetProcess: String, tweakFilter: String, blocks: [TweakBlock]) {
        self.id = id
        self.name = name
        self.bundleId = bundleId
        self.version = version
        self.targetProcess = targetProcess
        self.tweakFilter = tweakFilter
        self.blocks = blocks
    }
}

public struct TweakBlock: Codable, Identifiable {
    public let id: String
    public var type: String
    public var title: String
    public var positionX: Double
    public var positionY: Double
    public var targetClass: String?
    public var targetMethod: String?
    public var isClassMethod: Bool?
    public var returnType: String?
    public var message: String?
    public var logLevel: String?
    public var durationSeconds: Double?
    public var titleText: String?
    public var bodyText: String?
    public var propertyName: String?
    public var targetObject: String?
    public var value: String?
    public var condition: String?
    public var returnValue: String?
    public var customCode: String?
    public var childrenBlockIds: [String]?
    public var nextBlockId: String?
}
`;
}

/**
 * Generates Swift / SwiftUI App Source Code
 */
export function generateSwiftUICode(project: Project): string {
  return `//
// ${project.name.replace(/\s+/g, "")}App.swift
// Native iOS SwiftUI Application & Interactive Companion
// Target Process: ${project.targetProcess}
//

import SwiftUI
import Combine

@main
struct ${project.name.replace(/\s+/g, "")}App: App {
    @StateObject private var viewModel = TweakStudioViewModel()

    var body: some Scene {
        WindowGroup {
            MainStudioView()
                .environmentObject(viewModel)
                .preferredColorScheme(.dark)
        }
    }
}

// MARK: - Main Studio View
struct MainStudioView: View {
    @EnvironmentObject var viewModel: TweakStudioViewModel
    @State private var selectedTab = 0

    var body: some View {
        TabView(selection: $selectedTab) {
            CanvasView()
                .tabItem {
                    Label("Visual Canvas", systemImage: "square.grid.2x2.fill")
                }
                .tag(0)

            GeneratedCodeView()
                .tabItem {
                    Label("Logos Code", systemImage: "chevron.left.forwardslash.chevron.right")
                }
                .tag(1)

            RuntimeConsoleView()
                .tabItem {
                    Label("iOS Console", systemImage: "terminal.fill")
                }
                .tag(2)
        }
        .accentColor(Color(red: 0.22, green: 1.0, blue: 0.08))
    }
}

// MARK: - Canvas View
struct CanvasView: View {
    @EnvironmentObject var viewModel: TweakStudioViewModel

    var body: some View {
        NavigationStack {
            ZStack {
                Color.black.ignoresSafeArea()

                ScrollView([.horizontal, .vertical]) {
                    VStack(alignment: .leading, spacing: 16) {
                        ForEach(viewModel.project.blocks) { block in
                            SwiftUIBlockCard(block: block)
                        }
                    }
                    .padding()
                }
            }
            .navigationTitle("${project.name}")
            .toolbar {
                ToolbarItem(placement: .primaryAction) {
                    Button(action: {
                        viewModel.simulateExecution()
                    }) {
                        Label("Simulate", systemImage: "play.fill")
                            .foregroundColor(.black)
                            .padding(.horizontal, 12)
                            .padding(.vertical, 6)
                            .background(Color(red: 0.22, green: 1.0, blue: 0.08))
                            .cornerRadius(8)
                    }
                }
            }
        }
    }
}

// MARK: - Block Card Component
struct SwiftUIBlockCard: View {
    let block: TweakBlock

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text(block.type.uppercased())
                    .font(.caption2)
                    .bold()
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(block.type == "hook" ? Color.pink : Color.green)
                    .foregroundColor(.black)
                    .cornerRadius(4)

                Text(block.title)
                    .font(.system(.subheadline, design: .monospaced))
                    .bold()
                    .foregroundColor(.white)
                Spacer()
            }

            if let targetClass = block.targetClass {
                Text("Target: \(targetClass) (\(block.targetMethod ?? "viewDidAppear:"))")
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.gray)
            }

            if let msg = block.message {
                Text("Log: \"\(msg)\"")
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(Color(red: 0.22, green: 1.0, blue: 0.08))
            }
        }
        .padding(12)
        .frame(width: 280)
        .background(Color(red: 0.07, green: 0.07, blue: 0.07))
        .cornerRadius(10)
        .overlay(
            RoundedRectangle(cornerRadius: 10)
                .stroke(block.type == "hook" ? Color.pink : Color(red: 0.22, green: 1.0, blue: 0.08), lineWidth: 1)
        )
    }
}

// MARK: - Generated Code View
struct GeneratedCodeView: View {
    @EnvironmentObject var viewModel: TweakStudioViewModel

    var body: some View {
        NavigationStack {
            ScrollView {
                Text(viewModel.generatedLogos)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(Color(red: 0.22, green: 1.0, blue: 0.08))
                    .padding()
            }
            .background(Color.black.ignoresSafeArea())
            .navigationTitle("Logos Source")
        }
    }
}

// MARK: - Console Output View
struct RuntimeConsoleView: View {
    @EnvironmentObject var viewModel: TweakStudioViewModel

    var body: some View {
        NavigationStack {
            List(viewModel.consoleLogs, id: \\.self) { log in
                Text(log)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(log.contains("LOGOS") ? Color(red: 0.22, green: 1.0, blue: 0.08) : .white)
                    .listRowBackground(Color.black)
            }
            .listStyle(.plain)
            .background(Color.black.ignoresSafeArea())
            .navigationTitle("iOS System Log")
        }
    }
}

// MARK: - ViewModel
class TweakStudioViewModel: ObservableObject {
    @Published var project: TweakProject
    @Published var generatedLogos: String = ""
    @Published var consoleLogs: [String] = []

    init() {
        let sampleBlocks = [
            TweakBlock(id: "b1", type: "hook", title: "Hook SpringBoard", positionX: 100, positionY: 100, targetClass: "${project.targetProcess === 'SpringBoard' ? 'SBLockScreenManager' : 'UIViewController'}", targetMethod: "viewDidAppear:"),
            TweakBlock(id: "b2", type: "orig", title: "Call %orig", positionX: 100, positionY: 200),
            TweakBlock(id: "b3", type: "log", title: "Console Log", positionX: 100, positionY: 300, message: "${project.name} loaded successfully!")
        ]

        self.project = TweakProject(
            name: "${project.name}",
            bundleId: "${project.bundleId}",
            version: "${project.version}",
            targetProcess: "${project.targetProcess}",
            tweakFilter: "${project.tweakFilter}",
            blocks: sampleBlocks
        )

        self.generateCode()
    }

    func generateCode() {
        self.generatedLogos = """
        // Generated Logos Code for ${project.name}
        #import <UIKit/UIKit.h>

        %hook ${project.targetProcess === 'SpringBoard' ? 'SBLockScreenManager' : 'UIViewController'}
        - (void)viewDidAppear:(BOOL)animated {
            %orig;
            NSLog(@"[TheWorkshop] ${project.name} loaded!");
        }
        %end
        """
    }

    func simulateExecution() {
        consoleLogs.append("[LOGOS] Swizzling ${project.targetProcess} methods...")
        consoleLogs.append("[SYSTEM] Injected into ${project.bundleId}")
        consoleLogs.append("[NSLog] [TheWorkshop] ${project.name} active!")
    }
}
`;
}

/**
 * Generates Swift / Objective-C Interop Bridge Header
 */
export function generateSwiftBridgeHeader(project: Project): string {
  return `//
// ${project.name.replace(/\s+/g, "")}-Bridging-Header.h
// Objective-C & Swift Interoperability Bridge
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#import <os/log.h>

// Objective-C swizzling helper declarations
void WorkshopSwizzleInstanceMethod(Class targetClass, SEL originalSelector, SEL swizzledSelector);
void WorkshopLogSystemMessage(NSString *message);
`;
}

/**
 * Generates automated IPA Patching script for Jailed Modifications (using azule/optool & codesign)
 */
export function generateJailedPatchScript(project: Project): string {
  const assetBlocks = project.blocks.filter((b) => b.type === "replace_asset");
  const plistBlocks = project.blocks.filter((b) => b.type === "edit_plist");

  let assetCommands = "";
  assetBlocks.forEach((b) => {
    const asset = b.assetPath || "asset";
    const replace = b.replacementUrl || "custom.png";
    const targetApp = project.targetProcess;
    assetCommands += 'echo "  [+] Replacing asset ' + asset + '..."\n' +
      'cp -f "assets/' + replace + '" "extracted/Payload/' + targetApp + '.app/' + asset + '"\n';
  });

  let plistCommands = "";
  plistBlocks.forEach((b) => {
    const key = b.plistKey || "Key";
    const val = b.plistValue || "Value";
    const targetApp = project.targetProcess;
    plistCommands += 'echo "  [+] Injecting Info.plist key ' + key + ' = ' + val + '..."\n' +
      '/usr/libexec/PlistBuddy -c "Set :' + key + ' ' + val + '" "extracted/Payload/' + targetApp + '.app/Info.plist" || ' +
      '/usr/libexec/PlistBuddy -c "Add :' + key + ' string ' + val + '" "extracted/Payload/' + targetApp + '.app/Info.plist"\n';
  });

  const lines = [
    "#!/usr/bin/env bash",
    "# ==============================================================================",
    "# " + project.name + " - Jailed IPA Modification Patch Script",
    "# Generated by The Workshop (iOS Jailed Modding Engine)",
    "# Target Application: " + project.targetProcess + " (" + project.bundleId + ")",
    "# ==============================================================================",
    "",
    "set -e",
    "",
    'IPA_INPUT="TargetApp.ipa"',
    'IPA_OUTPUT="' + project.name.replace(/\s+/g, "") + '_Modified.ipa"',
    'DYLIB_NAME="' + project.name.replace(/\s+/g, "") + '.dylib"',
    "",
    'echo "========================================================"',
    'echo "  BUILDING JAILED MODIFICATION PACKAGE"',
    'echo "  Target: ' + project.targetProcess + '"',
    'echo "========================================================"',
    "",
    "# 1. Extract Target IPA Bundle",
    'echo "[1/4] Unpacking ' + project.targetProcess + ' IPA..."',
    "rm -rf extracted",
    'unzip -q "$IPA_INPUT" -d extracted',
    "",
    "# 2. Apply Asset Replacements",
    'echo "[2/4] Patching Bundle Assets & Resources..."',
    assetCommands || 'echo "  [i] No direct asset replacement blocks defined."',
    "",
    "# 3. Patch Info.plist & Metadata",
    'echo "[3/4] Modifying Info.plist Metadata..."',
    plistCommands || 'echo "  [i] No Info.plist modification blocks defined."',
    "",
    "# 4. Inject Dynamic Library & Resign",
    'echo "[4/4] Injecting Dylib via optool & resigning with Sideloadly/AltStore..."',
    'if [ -f "$DYLIB_NAME" ]; then',
    '    optool inject -s -t "extracted/Payload/' + project.targetProcess + '.app/' + project.targetProcess + '" -p "@executable_path/$DYLIB_NAME"',
    "fi",
    "",
    "cd extracted",
    'zip -qr "../$IPA_OUTPUT" Payload',
    "cd ..",
    "",
    'echo "========================================================"',
    'echo "  SUCCESS! Jailed IPA ready for sideloading:"',
    'echo "  Output: $IPA_OUTPUT"',
    'echo "========================================================"'
  ];

  return lines.join("\n");
}

/**
 * Generates Native Extension / WidgetKit SwiftUI Source Code
 */
export function generateNativeExtensionCode(project: Project): string {
  const widgetViews = project.blocks.filter((b) => b.type === "swiftui_view");
  const extensionConfigs = project.blocks.filter((b) => b.type === "extension_config");

  const extKind = extensionConfigs[0]?.extensionKind || "com.apple.widgetkit-extension";
  const extTitle = extensionConfigs[0]?.titleText || (project.name + " Extension");
  const projClean = project.name.replace(/\s+/g, "");

  let viewsCode = "";
  if (widgetViews.length > 0) {
    widgetViews.forEach((v) => {
      const vTitle = v.viewTitle || "WorkshopWidgetView";
      const vCode = v.swiftuiCode || 'Text("Native Extension View").font(.headline)';
      viewsCode += "\nstruct " + vTitle + ": View {\n" +
        "    var body: some View {\n" +
        "        VStack(alignment: .leading, spacing: 6) {\n" +
        "            HStack {\n" +
        '                Image(systemName: "sparkles")\n' +
        "                    .foregroundColor(.green)\n" +
        '                Text("' + extTitle + '")\n' +
        "                    .font(.caption)\n" +
        "                    .bold()\n" +
        "            }\n" +
        "            " + vCode + "\n" +
        "        }\n" +
        "        .padding()\n" +
        "        .background(Color.black)\n" +
        "    }\n" +
        "}\n";
    });
  } else {
    viewsCode = "\nstruct " + projClean + "WidgetEntryView: View {\n" +
      "    var body: some View {\n" +
      "        VStack {\n" +
      '            Text("' + project.name + '")\n' +
      "                .font(.headline)\n" +
      "                .foregroundStyle(.pink)\n" +
      '            Text("Native App Extension")\n' +
      "                .font(.caption)\n" +
      "                .foregroundStyle(.green)\n" +
      "        }\n" +
      "        .containerBackground(.fill.tertiary, for: .widget)\n" +
      "    }\n" +
      "}\n";
  }

  const mainView = widgetViews[0]?.viewTitle || (projClean + "WidgetEntryView");

  const lines = [
    "//",
    "// " + projClean + "Extension.swift",
    "// Native iOS App Extension & WidgetKit Target",
    "// Extension Point: " + extKind,
    "//",
    "",
    "import WidgetKit",
    "import SwiftUI",
    "",
    "@main",
    "struct " + projClean + "Extension: Widget {",
    '    let kind: String = "' + extKind + '"',
    "",
    "    var body: some WidgetConfiguration {",
    "        StaticConfiguration(kind: kind, provider: WorkshopProvider()) { entry in",
    "            " + mainView + "()",
    "        }",
    '        .configurationDisplayName("' + extTitle + '")',
    '        .description("' + (project.description || "Custom iOS Native Extension created with The Workshop.") + '")',
    "        .supportedFamilies([.systemSmall, .systemMedium, .accessoryCircular, .accessoryRectangular])",
    "    }",
    "}",
    "",
    "struct WorkshopEntry: TimelineEntry {",
    "    let date: Date",
    "}",
    "",
    "struct WorkshopProvider: TimelineProvider {",
    "    func placeholder(in context: Context) -> WorkshopEntry {",
    "        WorkshopEntry(date: Date())",
    "    }",
    "",
    "    func getSnapshot(in context: Context, completion: @escaping (WorkshopEntry) -> Void) {",
    "        completion(WorkshopEntry(date: Date()))",
    "    }",
    "",
    "    func getTimeline(in context: Context, completion: @escaping (Timeline<WorkshopEntry>) -> Void) {",
    "        let timeline = Timeline(entries: [WorkshopEntry(date: Date())], policy: .atEnd)",
    "        completion(timeline)",
    "    }",
    "}",
    viewsCode
  ];

  return lines.join("\n");
}

