//
//  CodeGeneration/ExtensionGenerator.swift
//  TheWorkshop-iOS
//  Native SwiftUI Extension Code Generator
//

import Foundation

public struct ExtensionGenerator: CodeGeneratorProtocol {
    public init() {}

    public func supportedTargetType() -> ProjectTargetType {
        return .nativeExtension
    }

    public func generateCode(for project: Project) -> String {
        var lines: [String] = []

        lines.append("//")
        lines.append("//  NativeExtension.swift")
        lines.append("//  \(project.name)")
        lines.append("//  Generated by The Workshop Native iOS Studio")
        lines.append("//")
        lines.append("")
        lines.append("import SwiftUI")
        lines.append("")

        let swiftuiBlocks = project.blocks.filter { $0.type == .swiftuiView }

        if swiftuiBlocks.isEmpty {
            lines.append("public struct WorkshopGeneratedExtensionView: View {")
            lines.append("    public var body: some View {")
            lines.append("        VStack(spacing: 12) {")
            lines.append("            Image(systemName: \"sparkles\")")
            lines.append("                .font(.largeTitle)")
            lines.append("                .foregroundStyle(Color(red: 0.22, green: 1.0, blue: 0.08))")
            lines.append("            Text(\"\(project.name)\")")
            lines.append("                .font(.headline)")
            lines.append("                .bold()")
            lines.append("            Text(\"Native SwiftUI extension running on iOS.\")")
            lines.append("                .font(.caption)")
            lines.append("                .foregroundStyle(.gray)")
            lines.append("        }")
            lines.append("        .padding()")
            lines.append("        .background(Color.black)")
            lines.append("        .cornerRadius(12)")
            lines.append("    }")
            lines.append("}")
        } else {
            for block in swiftuiBlocks {
                let title = block.viewTitle ?? "CustomExtension"
                let customCode = block.swiftuiCode ?? ""
                
                lines.append("public struct \(title)View: View {")
                if !customCode.isEmpty {
                    for codeLine in customCode.components(separatedBy: .newlines) {
                        lines.append("    \(codeLine)")
                    }
                } else {
                    lines.append("    public var body: some View {")
                    lines.append("        Text(\"\(title)\")")
                    lines.append("            .font(.title2)")
                    lines.append("            .foregroundStyle(Color(red: 0.22, green: 1.0, blue: 0.08))")
                    lines.append("    }")
                }
                lines.append("}")
                lines.append("")
            }
        }

        return lines.joined(separator: "\n")
    }
}
