//
//  CodeGeneration/JailedModGenerator.swift
//  TheWorkshop-iOS
//  Jailed IPA Patch Script Generator
//

import Foundation

public struct JailedModGenerator: CodeGeneratorProtocol {
    public init() {}

    public func supportedTargetType() -> ProjectTargetType {
        return .jailedMod
    }

    public func generateCode(for project: Project) -> String {
        var lines: [String] = []

        lines.append("#!/bin/bash")
        lines.append("# ==========================================")
        lines.append("# Jailed IPA Modification Patch Script")
        lines.append("# Project: \(project.name)")
        lines.append("# Target App Bundle: \(project.bundleId)")
        lines.append("# Generated by The Workshop Native iOS Studio")
        lines.append("# ==========================================")
        lines.append("set -e")
        lines.append("")
        lines.append("IPA_INPUT=\"$1\"")
        lines.append("IPA_OUTPUT=\"modified_\(project.name.lowercased().replacingOccurrences(of: " ", with: "_")).ipa\"")
        lines.append("WORK_DIR=$(mktemp -d)")
        lines.append("")
        lines.append("echo \"[+] Unpacking $IPA_INPUT...\"")
        lines.append("unzip -q \"$IPA_INPUT\" -d \"$WORK_DIR\"")
        lines.append("APP_PATH=$(find \"$WORK_DIR/Payload\" -name \"*.app\" -maxdepth 1)")
        lines.append("")

        let replaceBlocks = project.blocks.filter { $0.type == .replaceAsset }
        if !replaceBlocks.isEmpty {
            lines.append("# --- Asset Replacement Pass ---")
            for block in replaceBlocks {
                let asset = block.assetPath ?? "Assets.car"
                let repl = block.replacementUrl ?? "./new_asset.png"
                lines.append("echo \"[+] Replacing asset \(asset)...\"")
                lines.append("cp -f \"\(repl)\" \"$APP_PATH/\(asset)\"")
            }
            lines.append("")
        }

        let plistBlocks = project.blocks.filter { $0.type == .editPlist }
        if !plistBlocks.isEmpty {
            lines.append("# --- Info.plist Modification Pass ---")
            for block in plistBlocks {
                let key = block.plistKey ?? "CFBundleDisplayName"
                let val = block.plistValue ?? "ModifiedApp"
                lines.append("echo \"[+] Updating Plist key \(key) -> \(val)...\"")
                lines.append("plutil -replace \"\(key)\" -string \"\(val)\" \"$APP_PATH/Info.plist\"")
            }
            lines.append("")
        }

        lines.append("# --- Repackage & Code Sign ---")
        lines.append("echo \"[+] Packaging $IPA_OUTPUT...\"")
        lines.append("cd \"$WORK_DIR\" && zip -q -r \"$IPA_OUTPUT\" Payload/")
        lines.append("mv \"$WORK_DIR/$IPA_OUTPUT\" .")
        lines.append("rm -rf \"$WORK_DIR\"")
        lines.append("echo \"[✓] Successfully generated $IPA_OUTPUT for jailed installation!\"")

        return lines.joined(separator: "\n")
    }
}
