//
//  CodeGeneration/LogosGenerator.swift
//  TheWorkshop-iOS
//  Logos/Theos Code Generator Engine
//

import Foundation

public struct LogosGenerator: CodeGeneratorProtocol {
    public init() {}

    public func supportedTargetType() -> ProjectTargetType {
        return .jailbreakTweak
    }

    public func generateCode(for project: Project) -> String {
        var lines: [String] = []
        
        lines.append("//")
        lines.append("//  Tweak.x")
        lines.append("//  \(project.name)")
        lines.append("//  Generated by The Workshop Native iOS Studio")
        lines.append("//  Filter: \(project.tweakFilter)")
        lines.append("//")
        lines.append("")
        lines.append("#import <UIKit/UIKit.h>")
        lines.append("#import <os/log.h>")
        lines.append("")

        let hookBlocks = project.blocks.filter { $0.type == .hook }

        for hook in hookBlocks {
            let className = hook.targetClass ?? "TargetClass"
            let methodName = hook.targetMethod ?? "targetMethod"
            let isClassMethod = hook.isClassMethod ?? false
            let methodPrefix = isClassMethod ? "+" : "-"
            let returnType = hook.returnType ?? "void"

            lines.append("%hook \(className)")
            lines.append("")
            lines.append("\(methodPrefix) (\(returnType))\(methodName) {")

            // Generate child blocks logic
            if let childrenIds = hook.childrenBlockIds {
                for childId in childrenIds {
                    if let child = project.blocks.first(where: { $0.id == childId }) {
                        lines.append(contentsOf: generateBlockBody(child, indent: "    "))
                    }
                }
            } else {
                lines.append("    // Call original method implementation")
                lines.append("    %orig;")
            }

            lines.append("}")
            lines.append("%end")
            lines.append("")
        }

        if hookBlocks.isEmpty {
            lines.append("// No hook blocks placed on canvas yet.")
            lines.append("// Drag a 'Hook Method' block onto the canvas to begin.")
        }

        return lines.joined(separator: "\n")
    }

    private func generateBlockBody(_ block: Block, indent: String) -> [String] {
        var result: [String] = []

        switch block.type {
        case .orig:
            if let assign = block.assignToVar, !assign.isEmpty {
                result.append("\(indent)id \(assign) = %orig;")
            } else {
                result.append("\(indent)%orig;")
            }

        case .log:
            let msg = block.message ?? "Hook executed"
            result.append("\(indent)NSLog(@\"[TheWorkshop] \(msg)\");")

        case .delay:
            let secs = block.durationSeconds ?? 1.0
            result.append("\(indent)[NSThread sleepForTimeInterval:\(secs)];")

        case .modifyProperty:
            let obj = block.targetObject ?? "self"
            let prop = block.propertyName ?? "hidden"
            let val = block.value ?? "YES"
            result.append("\(indent)[\(obj) set\(prop.capitalized):\(val)];")

        case .conditional:
            let cond = block.condition ?? "YES"
            result.append("\(indent)if (\(cond)) {")
            result.append("\(indent)    NSLog(@\"[TheWorkshop] Condition met: \(cond)\");")
            result.append("\(indent)}")

        case .notification:
            let title = block.titleText ?? "Alert"
            let body = block.bodyText ?? "Message"
            result.append("\(indent)// Show HUD Notification")
            result.append("\(indent)NSLog(@\"[TheWorkshop] Banner: \(title) - \(body)\");")

        case .returnValue:
            let val = block.returnValue ?? "nil"
            result.append("\(indent)return \(val);")

        case .customLogos:
            let code = block.customCode ?? "// Custom Logos snippet"
            for line in code.components(separatedBy: .newlines) {
                result.append("\(indent)\(line)")
            }

        default:
            result.append("\(indent)// Unhandled action block: \(block.type.rawValue)")
        }

        return result
    }
}
